# ===============================================
# Configuraci�n del Servidor Web (Tomcat embebido)
# ===============================================
server.port=8080
# Define el puerto en el que la aplicaci�n escuchar� las peticiones HTTP.
# Por defecto es 8080, pero puedes cambiarlo a otro si es necesario.

# ===============================================
# Configuraci�n de la Base de Datos (DataSource)
# ===============================================

spring.data.mongodb.uri=mongodb://localhost:27017/todo-db
logging.level.org.springframework.data.mongodb.core=DEBUG


# ===============================================
# Configuraci�n de Logging (Opcional, pero �til para depurar)
# ===============================================
logging.level.org.springframework.web=INFO
# Nivel de log para los controladores web.
logging.level.org.hibernate.SQL=DEBUG
# Nivel de log para el SQL generado por Hibernate.
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Muestra los par�metros reales que Hibernate est� enviando a la base de datos (muy verboso).